import type { SocialPost } from "@/types";

export const MOCK_POSTS: SocialPost[] = [
  {
    id: "post-1",
    authorName: "Rahul Sharma",
    authorUsername: "rahul_sharma",
    authorAvatar: "",
    authorVerified: true,
    presence: "available-now",
    trustScore: 4.8,
    createdAt: new Date(Date.now() - 12 * 60000).toISOString(),
    sport: "football",
    location: "Andheri west, Mumbai",
    text: "What a finish tonight. Last-minute winner in the 5v5 and the whole turf erupted. This is why we play. Who is up for a rematch this weekend?",
    media: {
      type: "image",
      url: "https://images.unsplash.com/photo-1529900748604-07564a03e7a6?w=900&q=80",
      alt: "Football players celebrating on artificial turf at golden hour",
    },
    heartbeat: null,
    likes: 128,
    comments: [
      { id: "c1", authorName: "Priya Patel", authorAvatar: "", text: "That goal was insane!", createdAt: new Date(Date.now() - 8 * 60000).toISOString() },
      { id: "c2", authorName: "Arjun Nair", authorAvatar: "", text: "Rematch on, Saturday 6 PM?", createdAt: new Date(Date.now() - 5 * 60000).toISOString() },
    ],
    shares: 6,
    likedByMe: false,
    savedByMe: false,
    nearbyWantToJoin: 4,
  },
  {
    id: "post-2",
    authorName: "Mumbai Strikers",
    authorUsername: "mumbai_strikers",
    authorAvatar: "",
    authorVerified: true,
    presence: "today",
    trustScore: 4.9,
    createdAt: new Date(Date.now() - 35 * 60000).toISOString(),
    sport: "box-cricket",
    location: "Bandra, Mumbai",
    text: "Night box cricket under the lights. Tennis ball, proper gear, good vibes. We are two players short and the pitch is booked.",
    media: null,
    heartbeat: {
      type: "looking-for-player",
      label: "Looking for 2 players",
      playersNeeded: 2,
      joinUrl: "/games",
    },
    likes: 34,
    comments: [
      { id: "c3", authorName: "Vikram Singh", authorAvatar: "", text: "I can bring one more.", createdAt: new Date(Date.now() - 20 * 60000).toISOString() },
    ],
    shares: 2,
    likedByMe: true,
    savedByMe: false,
    nearbyWantToJoin: 7,
  },
  {
    id: "post-3",
    authorName: "Priya Patel",
    authorUsername: "priya_patel",
    authorAvatar: "",
    authorVerified: false,
    presence: "available-now",
    trustScore: 4.5,
    createdAt: new Date(Date.now() - 90 * 60000).toISOString(),
    sport: "badminton",
    location: "Powai, Mumbai",
    text: "First clean smash of the season and it felt perfect. Doubles partner carried me today, thank you Sneha.",
    media: {
      type: "image",
      url: "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=900&q=80",
      alt: "Badminton player mid-rally on a modern indoor court",
    },
    heartbeat: null,
    likes: 92,
    comments: [],
    shares: 4,
    likedByMe: false,
    savedByMe: true,
    nearbyWantToJoin: 0,
  },
  {
    id: "post-4",
    authorName: "Arjun Nair",
    authorUsername: "arjun_nair",
    authorAvatar: "",
    authorVerified: true,
    presence: "in-30-min",
    trustScore: 4.9,
    createdAt: new Date(Date.now() - 180 * 60000).toISOString(),
    sport: "box-cricket",
    location: "Shivaji park, Mumbai",
    text: "Match highlights from Sunday's league. Full send.",
    media: {
      type: "video",
      url: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=900&q=80",
      alt: "Box cricket match under floodlights",
    },
    heartbeat: null,
    likes: 210,
    comments: [
      { id: "c4", authorName: "Sneha Reddy", authorAvatar: "", text: "That cover drive though.", createdAt: new Date(Date.now() - 100 * 60000).toISOString() },
    ],
    shares: 18,
    likedByMe: false,
    savedByMe: false,
    nearbyWantToJoin: 3,
  },
];